# SITE CONFIGURATION
title: Les douceurs de petite Lulu # your site title
author: Lucile 
description: > # Meta description of Homepage
  Blog de recettes groumandes.
baseurl: "/douceurs" # the subpath of your site, e.g. /blog
url: "https://lesdouceursdepetitelulu.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Lucile Madoulaud
  links:
    - https://www.facebook.com/lucilemadoulaud
    - https://www.linkedin.com/in/lucilemadoulaud
    - https://github.com/lucileM


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

github_username:  lucilem # replace with your_github_username or comment to remove link from footer
instagram_username: little_and_lulu # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: madoulaud # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-TWHPB5L # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
