---
title: Les douceurs de petite Lulu
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Lucile
description: 'Blog de recettes groumandes.

'
baseurl: "/douceurs"
url: https://lesdouceursdepetitelulu.com
social:
  name: Lucile Madoulaud
  links:
  - https://www.facebook.com/lucilemadoulaud
  - https://www.linkedin.com/in/lucilemadoulaud
  - https://github.com/lucileM
navigation:
- name: Home
  link: "/"
- name: About
  link: "/about"
- name: Contact
  link: "/contact"
tagline: 'Modern Jekyll theme focused on speed performance &amp; SEO best practices

'
hero_img: posts/sleek_lg.jpg
email: your-email@domain.com
github_username: lucilem
instagram_username: little_and_lulu
disqus:
  shortname: madoulaud
google_tag_manager: GTM-TWHPB5L
service_worker: true
markdown: kramdown
highlighter: rouge
exclude:
- README.md
- node_modules
- script
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- vendor
- npm-debug.log
- gulpfile.js
- sleek.jpg
include:
- _pages
permalink: "/:title/"
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
- jekyll-seo-tag
